stages:
  data_ingestion:
    cmd: python src/CnnClassifier/pipeline/stage01.py
    deps:
      - src/cnnClassifier/pipeline/stage01.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Data


  prepare_base_model:
    cmd: python src/CnnClassifier/pipeline/stage02.py
    deps:
      - src/CnnClassifier/pipeline/stage02.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/CnnClassifier/pipeline/stage03.py
    deps:
      - src/CnnClassifier/pipeline/stage03.py
      - config/config.yaml
      - artifacts/data_ingestion/Data
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5


  evaluation:
    cmd: python src/CnnClassifier/pipeline/stage04.py
    deps:
      - src/CnnClassifier/pipeline/stage04.py
      - config/config.yaml
      - artifacts/data_ingestion/Data
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false